version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/ssl/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

