# Utilise l'image officielle CAS
FROM apereo/cas:latest

# Définir l'environnement de travail
WORKDIR /etc/cas

# Copier les fichiers de configuration CAS si nécessaire
COPY ./cas-overlay /etc/cas

# Exposer le port 8080 pour accéder à CAS
EXPOSE 8080

# Définir la commande de lancement
CMD ["java", "-jar", "/cas.war"]
